_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
definitions:
  block__admin_display:
    weight: -49
    menu_name: admin
    parent: system.admin_structure
    enabled: true
    expanded: false
  entity__node_type__collection:
    weight: -50
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  entity__menu__collection:
    weight: -48
    menu_name: admin
    parent: system.admin_structure
    expanded: false
    enabled: true
  user__admin_index:
    menu_name: admin
    parent: entity.user.collection
    weight: -20
    expanded: false
    enabled: true
  system__admin_config_system:
    weight: -47
    menu_name: admin
    parent: system.admin_config
    expanded: false
    enabled: true
  system__admin_config_content:
    weight: -45
    menu_name: admin
    parent: system.admin_config
    expanded: false
    enabled: true
  system__admin_config_ui:
    weight: -46
    menu_name: admin
    parent: system.admin_config
    expanded: false
    enabled: true
  system__admin_config_development:
    weight: -48
    menu_name: admin
    parent: system.admin_config
    enabled: true
    expanded: false
  system__admin_config_media:
    weight: -44
    menu_name: admin
    parent: system.admin_config
    expanded: false
    enabled: true
  system__admin_config_search:
    weight: -43
    menu_name: admin
    parent: system.admin_config
    expanded: false
    enabled: true
  system__admin_config_regional:
    weight: -42
    menu_name: admin
    parent: system.admin_config
    expanded: false
    enabled: true
  system__admin_config_services:
    weight: -41
    menu_name: admin
    parent: system.admin_config
    expanded: false
    enabled: true
  system__admin_config_workflow:
    weight: -40
    menu_name: admin
    parent: system.admin_config
    expanded: false
    enabled: true
  update__status:
    menu_name: admin
    parent: system.modules_list
    weight: -50
    expanded: false
    enabled: true
  entity__config_split__collection:
    weight: -47
    parent: config.sync
    menu_name: admin
    expanded: false
    enabled: true
  config__sync:
    weight: -50
    parent: system.admin_config
    menu_name: admin
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:config__import':
    weight: -50
    menu_name: admin
    parent: config.sync
    enabled: true
    expanded: false
  'admin_toolbar_tools__extra_links:config__export':
    weight: -49
    menu_name: admin
    parent: config.sync
    expanded: false
    enabled: true
  config_ignore__settings:
    weight: -48
    menu_name: admin
    parent: config.sync
    expanded: false
    enabled: true
