_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  better_exposed_filters: 0
  bigmenu: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  coffee: 0
  config: 0
  config_filter: 0
  config_split: 0
  contextual: 0
  crop: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  decorative_image_widget: 0
  dynamic_page_cache: 0
  easy_responsive_images: 0
  editor: 0
  entity_save_and_addanother: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  fontawesome: 0
  fontawesome_menu_icons: 0
  gin_login: 0
  gin_toolbar: 0
  image: 0
  imageapi_optimize: 0
  imageapi_optimize_gd: 0
  inline_form_errors: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_draggable: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  link: 0
  linkit: 0
  media: 0
  media_bulk_upload: 0
  media_file_delete: 0
  media_library: 0
  media_library_edit: 0
  menu_fast_edit: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rabbit_hole: 0
  redirect: 0
  redirect_404: 0
  redirect_domain: 0
  responsive_favicons: 0
  responsive_image: 0
  sdc: 0
  seckit: 0
  serialization: 0
  settings_tray: 0
  speedboxes: 0
  structure_sync: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  view_unpublished: 0
  views_ajax_history: 0
  views_ui: 0
  pathauto: 1
  views: 10
  publication_date: 99
  minimal: 1000
theme:
  claro: 0
  gin: 0
  stable9: 0
  module_monster: 0
profile: minimal
